= btrfs-scrub-scheduler

Smart scheduler for BTRFS scrubbing.
Make `btrfs scrub` run only during the maintenance window.

*Problem:*

You want to periodically scrub your BTRFS filesystems,
but it takes too long to scrub them all at once
and the IO is overloaded during scrubbing.

*Solution:*

Use this scheduler to run `btrfs scrub` only during the maintenance window.

== Implementation

Scrubbing is run only during the maintenance window and distributed over several days:

* `btrfs-scrub-scheduler` is supposed to run daily at the beginning of the maintenance window.
* track the last scrub date of each filesystem to know when a scrub should be run next time
* interrupt scrubbing at the end of the maintenance window
* resume scrubbing on the next run

== Installation

=== Prerequisites

You will need the following tools on your server:

* Node.js to run the scheduler

Running this should suffice on a recent Debian or Ubuntu:

----
apt install nodejs
----

=== Setup

1. Download the latest release:
+
----
wget -O /usr/local/bin/btrfs-scrub-scheduler https://github.com/antrew/btrfs-scrub-scheduler/releases/latest/download/btrfs-scrub-scheduler
chmod +x /usr/local/bin/btrfs-scrub-scheduler
----
2. Configure the period and filesystems you want to scrub by creating a configuration file `/etc/btrfs-scrub-scheduler/config.json` that looks like this:
+
----
{
  "period": 30,
  "maxDuration": "PT7H",
  "filesystems": [
    "/",
    "/mnt/example"
  ]
}
----
3. Create a cronjob that will start the scheduler daily at the beginning of the maintenance window.
+
----
0 0 * * * /usr/local/bin/btrfs-scrub-scheduler
----

== Configuration Parameters

=== period

How often to scrub filesystems.
If the last scrub of a filesystem finished less than `period` days ago, the filesystem will not be scrubbed.
E.g., `"period": 90` would scrub each filesystem every 3 months.

Accepted values: number of days or ISO 8601.

Examples for a monthly scrub:
----
"period": 30
"period": "30"
"period": "P30D"
----

=== maxDuration (optional)

Maximum duration of a single scrub run.
If the scrub takes longer than `maxDuration`, it will be interrupted and resumed on the next script execution.
E.g., `"maxDuration": "6:30"` will cancel the scrub after 6,5 hours.
If no `maxDuration` is configured, a scrub run will not be interrupted.

Accepted values: "HH:MM", "HH:MM:SS" or ISO 8601.

Examples for 7,5 hours:
----
"maxDuration": "7:30"
"maxDuration": "7:30:00"
"maxDuration": "PT7H30M"
----
